import type {
  RemodelingCatalogItem,
  RemodelingPriceCatalog,
  RemodelingScenarioTier,
  RemodelingWorkScope,
} from "@/lib/types/domain";

function item(
  key: string,
  category: string,
  name: string,
  args: {
    workScope: RemodelingWorkScope;
    materialManwon: number;
    laborManwon: number;
    diy?: boolean;
    effectNote: string;
    scenarioTiers: RemodelingScenarioTier[];
    rentUplift?: { oneRoom?: number; oneHalfRoom?: number; twoRoom?: number };
    efficiencyScore?: number;
  },
): RemodelingCatalogItem {
  return {
    key,
    category,
    item: name,
    workScope: args.workScope,
    materialManwon: args.materialManwon,
    laborManwon: args.laborManwon,
    diy: args.diy ?? false,
    effectNote: args.effectNote,
    scenarioTiers: args.scenarioTiers,
    rentUpliftManwon: {
      oneRoom: args.rentUplift?.oneRoom ?? 0,
      oneHalfRoom: args.rentUplift?.oneHalfRoom ?? 0,
      twoRoom: args.rentUplift?.twoRoom ?? 0,
    },
    efficiencyScore: args.efficiencyScore ?? 0,
  };
}

/** 대전·다가구 내부 수리 기본 단가 (만원, 호실·원룸 기준 unless noted) */
export const DEFAULT_REMODELING_PRICE_CATALOG: RemodelingPriceCatalog = {
  regionId: "daejeon",
  regionLabel: "대전광역시 (다가구·원룸)",
  sourceNote:
    "공실 즉시 수익화·거주 중 순차 공사·건물 공용 보수 기준. 현장·업체 견적에 맞게 항목·금액을 수정하세요.",
  updatedAt: new Date().toISOString().slice(0, 10),
  items: [
    item("clean-pro", "청소·준비", "입주 전 전문 청소", {
      workScope: "full_replace",
      materialManwon: 0,
      laborManwon: 20,
      effectNote: "첫 공실 필수",
      scenarioTiers: ["minimal", "balanced", "full"],
      rentUplift: { oneRoom: 1 },
      efficiencyScore: 9,
    }),
    item("clean-diy", "청소·준비", "셀프 청소·폐기물 정리", {
      workScope: "reuse",
      materialManwon: 3,
      laborManwon: 0,
      diy: true,
      effectNote: "비용 최소",
      scenarioTiers: ["minimal"],
      efficiencyScore: 7,
    }),
    item("wall-paper-full", "도배·벽", "전체 도배 (합지)", {
      workScope: "full_replace",
      materialManwon: 15,
      laborManwon: 25,
      effectNote: "첫인상·냄새 제거",
      scenarioTiers: ["minimal", "balanced", "full"],
      rentUplift: { oneRoom: 3, oneHalfRoom: 4, twoRoom: 5 },
      efficiencyScore: 10,
    }),
    item("wall-paper-partial", "도배·벽", "손상 벽면만 도배", {
      workScope: "partial",
      materialManwon: 7,
      laborManwon: 12,
      effectNote: "국소 보수",
      scenarioTiers: ["minimal", "balanced"],
      rentUplift: { oneRoom: 1 },
      efficiencyScore: 6,
    }),
    item("wall-mold", "도배·벽", "곰팡이·벽지 제거 후 도배", {
      workScope: "partial",
      materialManwon: 10,
      laborManwon: 20,
      effectNote: "누수·결로 후속",
      scenarioTiers: ["balanced", "full"],
      rentUplift: { oneRoom: 2 },
      efficiencyScore: 8,
    }),
    item("floor-vinyl", "바닥", "PVC 장판 (원룸)", {
      workScope: "full_replace",
      materialManwon: 20,
      laborManwon: 10,
      diy: true,
      effectNote: "저비용 바닥",
      scenarioTiers: ["minimal", "balanced"],
      rentUplift: { oneRoom: 2 },
      efficiencyScore: 8,
    }),
    item("floor-spc", "바닥", "SPC 바닥재 (방수)", {
      workScope: "full_replace",
      materialManwon: 35,
      laborManwon: 10,
      diy: true,
      effectNote: "욕실 인접 권장",
      scenarioTiers: ["balanced", "full"],
      rentUplift: { oneRoom: 3, oneHalfRoom: 4 },
      efficiencyScore: 9,
    }),
    item("floor-wood", "바닥", "강화마루", {
      workScope: "full_replace",
      materialManwon: 25,
      laborManwon: 12,
      effectNote: "거실·투룸",
      scenarioTiers: ["balanced", "full"],
      rentUplift: { twoRoom: 4 },
      efficiencyScore: 7,
    }),
    item("floor-tile-bath", "바닥", "욕실 타일 부분 교체", {
      workScope: "partial",
      materialManwon: 25,
      laborManwon: 35,
      effectNote: "누수·기존 타일 들뜸",
      scenarioTiers: ["balanced", "full"],
      efficiencyScore: 6,
    }),
    item("window-inner", "창호·문", "내창(단열) 추가", {
      workScope: "partial",
      materialManwon: 30,
      laborManwon: 13,
      effectNote: "거주 중 대안",
      scenarioTiers: ["minimal", "balanced"],
      rentUplift: { oneRoom: 2 },
      efficiencyScore: 8,
    }),
    item("window-pvc", "창호·문", "PVC 이중창 교체", {
      workScope: "full_replace",
      materialManwon: 80,
      laborManwon: 40,
      effectNote: "냉난방·소음",
      scenarioTiers: ["balanced", "full"],
      rentUplift: { oneRoom: 4, oneHalfRoom: 5, twoRoom: 6 },
      efficiencyScore: 9,
    }),
    item("window-screen", "창호·문", "방충망 교체", {
      workScope: "partial",
      materialManwon: 4,
      laborManwon: 0,
      diy: true,
      effectNote: "즉시 체감",
      scenarioTiers: ["minimal", "balanced", "full"],
      efficiencyScore: 7,
    }),
    item("door-lock", "창호·문", "도어락·손잡이 교체", {
      workScope: "partial",
      materialManwon: 13,
      laborManwon: 5,
      diy: true,
      effectNote: "보안·편의",
      scenarioTiers: ["minimal", "balanced", "full"],
      efficiencyScore: 8,
    }),
    item("door-interior", "창호·문", "실내문·문틀 수리", {
      workScope: "partial",
      materialManwon: 15,
      laborManwon: 10,
      effectNote: "개폐 불량",
      scenarioTiers: ["balanced", "full"],
      efficiencyScore: 5,
    }),
    item("kitchen-sink-film", "주방·욕실", "싱크대 상판·캐비닛 필름", {
      workScope: "partial",
      materialManwon: 7,
      laborManwon: 0,
      diy: true,
      effectNote: "주방 인상",
      scenarioTiers: ["minimal", "balanced"],
      rentUplift: { oneRoom: 1 },
      efficiencyScore: 8,
    }),
    item("kitchen-faucet", "주방·욕실", "주방 수전 교체", {
      workScope: "partial",
      materialManwon: 5,
      laborManwon: 5,
      effectNote: "누수·녹",
      scenarioTiers: ["minimal", "balanced", "full"],
      efficiencyScore: 6,
    }),
    item("bath-faucet", "주방·욕실", "욕실 수전·샤워기", {
      workScope: "partial",
      materialManwon: 8,
      laborManwon: 5,
      effectNote: "수압·온수",
      scenarioTiers: ["minimal", "balanced", "full"],
      efficiencyScore: 6,
    }),
    item("bath-silicone", "주방·욕실", "욕실 실리콘·줄눈", {
      workScope: "partial",
      materialManwon: 2,
      laborManwon: 0,
      diy: true,
      effectNote: "곰팡이 예방",
      scenarioTiers: ["minimal", "balanced", "full"],
      efficiencyScore: 9,
    }),
    item("bath-waterproof", "주방·욕실", "욕실 부분 방수", {
      workScope: "partial",
      materialManwon: 15,
      laborManwon: 25,
      effectNote: "누수 의심 시",
      scenarioTiers: ["balanced", "full"],
      efficiencyScore: 7,
    }),
    item("bath-boiler-check", "주방·욕실", "보일러·온수기 점검·청소", {
      workScope: "reuse",
      materialManwon: 0,
      laborManwon: 8,
      effectNote: "겨울 공실 대비",
      scenarioTiers: ["minimal", "balanced"],
      efficiencyScore: 6,
    }),
    item("elec-led", "전기·조명", "LED 조명 전체 교체", {
      workScope: "full_replace",
      materialManwon: 20,
      laborManwon: 8,
      diy: true,
      effectNote: "밝기·전기료",
      scenarioTiers: ["minimal", "balanced", "full"],
      rentUplift: { oneRoom: 2 },
      efficiencyScore: 10,
    }),
    item("elec-outlet", "전기·조명", "콘센트·배선 점검", {
      workScope: "partial",
      materialManwon: 5,
      laborManwon: 10,
      effectNote: "안전",
      scenarioTiers: ["balanced", "full"],
      efficiencyScore: 5,
    }),
    item("elec-breaker", "전기·조명", "누전차단기·분전반", {
      workScope: "partial",
      materialManwon: 15,
      laborManwon: 15,
      effectNote: "구형 배선",
      scenarioTiers: ["full"],
      efficiencyScore: 4,
    }),
    item("ac-wall", "전기·조명", "벽걸이 에어컨 설치", {
      workScope: "full_replace",
      materialManwon: 45,
      laborManwon: 15,
      effectNote: "여름 공실",
      scenarioTiers: ["balanced", "full"],
      rentUplift: { oneRoom: 3, oneHalfRoom: 4 },
      efficiencyScore: 8,
    }),
    item("ac-built", "전기·조명", "빌트인·시스템 에어컨", {
      workScope: "full_replace",
      materialManwon: 65,
      laborManwon: 0,
      effectNote: "고급 호실",
      scenarioTiers: ["full"],
      rentUplift: { twoRoom: 5 },
      efficiencyScore: 6,
    }),
    item("plumb-pipe", "배관", "노후 배관 부분 교체", {
      workScope: "partial",
      materialManwon: 20,
      laborManwon: 30,
      effectNote: "누수·수압",
      scenarioTiers: ["full"],
      efficiencyScore: 5,
    }),
    item("furniture-closet", "가구·수납", "붙박이·수납 보수", {
      workScope: "partial",
      materialManwon: 20,
      laborManwon: 15,
      effectNote: "공간 활용",
      scenarioTiers: ["balanced", "full"],
      efficiencyScore: 5,
    }),
    item("roof-water", "건물 공용", "옥상 방수", {
      workScope: "full_replace",
      materialManwon: 600,
      laborManwon: 0,
      effectNote: "건물 전체",
      scenarioTiers: ["full"],
      efficiencyScore: 8,
    }),
    item("ext-paint", "건물 공용", "외벽 도장·코팅", {
      workScope: "full_replace",
      materialManwon: 450,
      laborManwon: 0,
      effectNote: "건물 전체",
      scenarioTiers: ["full"],
      efficiencyScore: 6,
    }),
    item("common-door", "건물 공용", "공동현관 도어·도장", {
      workScope: "partial",
      materialManwon: 150,
      laborManwon: 0,
      effectNote: "첫인상",
      scenarioTiers: ["balanced", "full"],
      efficiencyScore: 7,
    }),
    item("stairs-led", "건물 공용", "복도·계단 LED·도장", {
      workScope: "partial",
      materialManwon: 220,
      laborManwon: 0,
      effectNote: "공용부",
      scenarioTiers: ["balanced", "full"],
      efficiencyScore: 6,
    }),
    item("cctv", "건물 공용", "CCTV·보안", {
      workScope: "full_replace",
      materialManwon: 120,
      laborManwon: 0,
      effectNote: "임차인 안심",
      scenarioTiers: ["full"],
      efficiencyScore: 5,
    }),
  ],
};
